USE codeup_test_db;
INSERT INTO albums(artist, name, release_date, sales, genre )
values ('Led Zeppelin', 'Led Zeppelin IV', 1971, 30.4,'Hard rock, heavy metal, folk rock'),
       ('Shania Twain', 'Come on over', 1997, 30.4,'Country pop'),
       ('Eagles', 'Hotel California', 1997, 31.8, 'Soft rock'),
       ('AC/DC', 'Back in Black', 1980, 30.1,'Hard rock'),
       ('Michael Jackson', 'Thriller', 1982, 50.2, 'Pop, disco, funk, rock'),
       ('The Beatles', 'Abbey Road,', 1969,	16.9, 'Rock'),
       ('Michael Jackson',	'Dangerous',	1991, 17.0,	'New jack swing, R&B and pop'),
       ('The Beatles',	'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 18.3,n'Rock'),
       ('Pink Floyd', 'The Wall', 1979, 18.9,'Progressive rock'),
       ('Madonna',	'The Immaculate Collection', 1990, 19.8, 'Pop, dance'),
       ('Santana',	'Supernatural', 1999, 20.8, 'Latin rock'),
       ('Dire Straits',	'Brothers in Arms',	1985, 21.1,	'Roots rock, blues rock, soft rock'),
       ('ABBA',	'Gold: Greatest Hits',	1992, 21.6,	'Pop, disco'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 22, 'Heartland rock'),
       ('Guns N'' Roses',	'Appetite for Destruction',	1987, 22.8, 'Hard rock'),
       ('Bob Marley & The Wailers',	'Legend: The Best of Bob Marley & The Wailers',	1984, 22.9,	'Reggae'),
    ('Celine Dion',	'Let''s Talk About Love', 1997, 19.5, 'Pop, soft rock'),
    ('Metallica',	'Metallica', 1991, 22.7, 'Heavy metal'),
    ('The Beatles',	'1', 2000, 23.2, 'Rock'),
    ('Adele', '21',	2011, 27.1,	'Pop, soul'),
    ('Celine Dion',	'Falling into You',	1996, 21.1,	'Pop, soft rock'),
    ('Various artists',	'Dirty Dancing', 1987, 24.1, 'Pop, rock, R&B'),
    ('Alanis Morissette', 'Jagged Little Pill',	1995, 25.4,	'Alternative rock'),
    ('Meat Loaf',	'Bat Out of Hell',	1977, 22, 'Hard rock, glam rock, progressive rock'),
    ('Michael Jackson',	'Bad', 1987, 21.1, 	'Pop, rhythm and blues, funk and rock'),
    ('Bee Gee',	'Saturday Night Fever',	1977, 22.1,	'Disco'),
    ('Fleetwood Mac',	'Rumours', 1977, 29.3,	'Soft rock'),
    ('Pink Floyd',	'The Dark Side of the Moon', 1973, 24.8, 'Progressive rock'),
    ('Whitney Houston',  'The Bodyguard', 1992, 28.7, 'R&B, soul, pop, soundtrack');

